# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            andrew roy chen
tagline:          'works by Andrew Roy'
description:      'front-end engineer'
url:              http://localhost:4000/
baseurl:          /

author:
  name:           'Andrew Roy Chen'
  url:            'hai.anzu.xyz'

# Collections
collections:
- projects


# Custom vars
version:          2.1.x

github:
  main:           https://github.com/uncleoptimus
  repo:           https://github.com/uncleoptimus/hyde-arc

linkedin:         https://www.linkedin.com/in/anzuchen
